import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/SessionProvider";
import { cn } from "@/utils/style";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={cn("flex h-screen w-screen text-sm lg:text-base")}>
        <SessionProvider session={session}>
          <div className="flex flex-1 flex-col">
            <Header />
            <div className="flex flex-1 flex-col overflow-y-auto">
              <main className="container flex flex-1 flex-col">{children}</main>
              {/* Footer */}
            </div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
